- name: Deploy Docker Image from Docker Hub
  hosts: productionservers
  gather_facts: false
  remote_user: root
  tasks:
    - name: Stopping the Container
      docker_container:
        name: production
        image: sachinsebastian114/capstone:latest
        state: stopped

    - name: Removing the Container
      docker_container:
        name: production
        image: sachinsebastian114/capstone:latest
        state: absent

    - name: Removing Docker Image
      docker_image:
        name: sachinsebastian114/capstone:latest
        state: absent

    - name: Log in to Docker Hub
      docker_login:
        username: sachinsebastian114
        password: Sachin@6865

    - name: Pull Docker image from Docker Hub
      docker_image:
        name: sachinsebastian114/capstone:latest
        source: pull

    - name: Run Docker container
      docker_container:
        name: production
        image: sachinsebastian114/capstone:latest
        state: started
        ports:
          - "80:80"
